### ISSUE TITLE
Minimap / Broker right-click error

### ISSUE THREAD

**Issue by Road-block** [Tojaso/Buffle#2]
At a guess this method is missing from Main.lua

```lua
-- Toggle visibility of previews
function MOD.TogglePreviews()
	MOD.showPreviews = not MOD.showPreviews
	MOD.CheckPreviews()
	MOD.UpdateAll()
end
```

version 1.0 errors when right-clicking the button

**Comment by Tojaso** [comment]
Thank you for catching and reporting this! I must have gotten distracted while reorganizing some code snippets...
Fixed in v1.0.1
